## TEST validate should fail if matNr only has 7 digits
POST {{host}}/validate
Content-Type: application/json

{
  "path": ["universities", "tuwien", "students", "0", "matNr"],
  "value": {
    "universities": {
      "tuwien": {
        "students": [
          {
            "matNr": "1211987"
          }
        ]
      }
    }
  }
}

### TEST inspect should work
POST {{host}}/inspect
Content-Type: application/json

{
  "path": ["universities", "tuwien", "students", "0", "name"],
  "value": {
    "universities": {
      "tuwien": {
        "students": [
          {
            "matNr": "12119877",
            "name": "Leon K",
            "semester": 5,
            "active": true
          }
        ]
      }
    }
  }
}

### TEST summarize should work
POST {{host}}/summarize
Content-Type: application/json

{
  "value": {
    "universities": {
      "tuwien": {
        "students": [
          {
            "matNr": "12119877"
          }
        ]
      }
    }
  }
}